gateware/scripts: fix BD wrapper as top-level
Without this, Vivado will likely complain
with:

70160 - SDK - [Hsi 55-2023] No IPI block design hardware
handoff files present in the hardware definition file.

The solution is to force the generated BD wrapper as the
top-level module and file.

Reference: https://support.xilinx.com/s/article/70160?language=en_US

"""
TITLE
70160 - SDK - [Hsi 55-2023] No IPI block design hardware handoff files
present in the hardware definition file.

DESCRIPTION
When creating a Hardware Platform in SDK, I see the following
errors in the log console:

ERROR: [Hsi 55-2023] No IPI block design hardware handoff
files present in the hardware definition file <path>/<hdf_filename>.hdf
ERROR: [Hsi 55-1451] Error: running open_hw_design.
ERROR: [Common 17-39] 'open_hw_design' failed due to earlier errors.

What is the reason for this?

SOLUTION
This happens if the Hardware has been exported from Vivado with the
Block Design (BD) as top level.
"""